baseurl = "/"
title = "cultures numériques"
theme = "culturesNumeriquesTheme"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Persons"
    pre = "persons"
    url = "/persons/"
    weight = 1
  [[menu.main]]
    name = "Organization"
    pre = "organizations"
    url = "/organizations/"
    weight = 1
   [[menu.main]]
    name = "Évenements"
    pre = "events"
    url = "/events/"
    weight = 1