baseurl = "/"
title = "Cultures Numériques"
theme = "culturesNumeriquesTheme"

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Persons"
    pre = "persons"
    url = "/persons/"
    weight = 1
  [[menu.main]]
    name = "Organization"
    pre = "organizations"
    url = "/organizations/"
    weight = 1
   [[menu.main]]
    name = "Évenements"
    pre = "events"
    url = "/events/"
    weight = 1

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'persons'
    weight = 100
